

services:
  web:
    image: 590184076390.dkr.ecr.eu-west-2.amazonaws.com/flask-sql:latest
    ports:
      - "5002:5002"
    depends_on:
      - mydb

  mydb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw





