services:
  web:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - redisdb
    environment:
      - REDIS_HOST=redisdb
      - REDIS_PORT=6379

  redisdb:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdb-data:/data

volumes:
  redisdb-data: